name = "box-this-lap-guides"
main = "src/index.js"
compatibility_date = "2026-08-19"

[vars]
ALLOWED_ORIGINS = "https://wyattjones-wnc.github.io,http://localhost:8000,http://127.0.0.1:8000"

[env.preview]
name = "box-this-lap-guides-preview"

[env.preview.vars]
ALLOWED_ORIGINS = "https://wyattjones-wnc.github.io,http://localhost:8000,http://127.0.0.1:8000"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "guides-progress-preview"
database_id = "6faab5e7-138f-43a8-95e0-acd2ac8e8b2d"
