name = "box-this-lap-formula-one"
main = "src/index.js"
compatibility_date = "2026-09-10"

[[d1_databases]]
binding = "DB"
database_name = "formula-one"
database_id = "b3e28ed0-a9c9-43d1-a6cb-ae22b8a181a6"

[[services]]
binding = "AUTH_SERVICE"
service = "box-this-lap-rankings"

[vars]
ALLOWED_ORIGINS = "https://wyattjones-wnc.github.io,http://localhost:8000,http://127.0.0.1:8000"
AUTH_VERIFY_URL = "https://box-this-lap-rankings.boxthislap.workers.dev/api/auth/verify"
ADMIN_MANAGER_IDS = "6"
JOLPICA_BASE_URL = "https://api.jolpi.ca/ergast/f1"
GOOGLE_SHEETS_EXPORT_ENDPOINT = "https://script.google.com/macros/s/AKfycbyPCg9hlmB82fHaF_zF3KjEu2rrqFoFJzq-flKjX3wmX_8jEXNL15nGRFn_VQBiA8yT/exec"
